### ISSUE TITLE
Do you plan to merge changes back to upstream?

### ISSUE THREAD

**Issue by zdila** [mapycz/mapnik#2]
I see you added many improvements against upstream. Do you plan to merge them back?

**Comment by talaj** [comment]
Most of them are already part of upstream. Do you have some particular feature in mind?

**Comment by zdila** [comment]
Thanks. Nothing particular, I would just like to use the best of both worlds :-). Do you plan no merge all to upstream, or you want to keep something only in mapycz version? And do you also merge from upstream to mapycz?

**Comment by talaj** [comment]
I would like to merge all changes to the upstream because they are actually actively used on mapy.cz, so those features can be useful for others. But some features are not yet merged due to my feeling that the code is not ready to become upstream or just due to lack of time.

Regarding merging from upstream to mapycz, I prefer stability over newest code. Even though Mapnik development is now minimal since Mapbox moved their work force to their client side renderers, I don't merge with upstream currently, only cherry-picks interesting changes.

What I would like to see in upstream are improvements in PDF and SVG rendering through Cairo and things related to printing. I have made some work in this area last year and I think that this is area where Mapnik has no competition in open source world. https://github.com/mapnik/mapnik/pull/4009 is an example of such improvement.

**Comment by zdila** [comment]
Thanks @talaj for valuable information. You do the great job!

> What I would like to see in upstream are improvements in PDF and SVG rendering...

Fresh from osm cz mailing list:
https://lists.openstreetmap.org/pipermail/talk-cz/2019-February/020787.html

In our Freemap Slovakia portal we already use PDF (vector) exporting feature of mapnik - https://www.freemap.sk/?map=13/48.721773/21.241121&layers=X&show=export-pdf
